// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: esp32

#include "ui.h"

void toggleLED(lv_event_t *e)
{
	digitalWrite(33, 1); // sets the digital pin 13 on
	delay(1000);		 // waits for a second
	digitalWrite(33, 0); // sets the digital pin 13 off
	delay(1000);
}

void setOnOff(lv_event_t * e)
{
	// Your code here
}

void setSpeed(lv_event_t * e)
{
	// Your code here
}
